---
title: "Natural Parks"
author: "Kev"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries
library(dplyr) # data wrangling
library(tidyr) # data wrangling
library(ggplot2) # data visualisation
library(sf) # simple features - geospatial geometries
library(osmdata) # obtaining OpenStreetMap vector data
library(units) # working with units
library(mapview) # interactive geometry viewing
library(ggmap) # downloading raster maps from a variety of sources
library(ggspatial) # map backgrounds and annotations for ggplot
library(tmap) # static/interactive map library with ggplot-like syntax


install.packages("mapview")
install.packages("ggspatial")
install.packages("tmap")

# Get the polygon for Nairobi
city_polygon <- getbb("City of Nairobi",
                      featuretype = "settlement",
                      format_out = "polygon")

# Get the rectangular bounding box
city_rect <- getbb("City of Nairobi", featuretype = "settlement")

# Get the data from OSM 
greensp_osm <-
  opq(bbox = city_polygon) %>%  # start query, input bounding box
  add_osm_feature(key = "leisure",
                  value = c("park", "nature_reserve", "golf_course")) %>%
  # we want to extract "leisure" features that are park, nature reserve or a golf course
  osmdata_sf() %>%
  # query OSM and return as simple features (sf)
  trim_osmdata(city_polygon)
# limit data to the Nairobi polygon instead of the rectangular bounding box


# Look at query output
greensp_osm

# In the results, polygons and multipolygons are likely of interest. A look into it:
glimpse(greensp_osm$osm_polygons)
glimpse(greensp_osm$osm_multipolygons)


# Convert POLYGON to MULTIPOLYGON and bind into one sf object.
greensp_sf <- bind_rows(st_cast(greensp_osm$osm_polygons, "MULTIPOLYGON"),
                        greensp_osm$osm_multipolygons) %>%
  select(name, osm_id, leisure)

# Plot coloured by the value of leisure
plot(greensp_sf["Leisure_Areas"])

```